using UnityEngine;

public class DemoCaller : MonoBehaviour
{
    public FastAPIClient fastAPIClient; // Drag your TTSManager GameObject here in the Inspector

    void Start()
    {
        if (fastAPIClient != null)
        {
            fastAPIClient.RequestSpeech("Hello from Unity! This sound is generated by Python. If you like this, please give a thumbs up to the video and subscribe to the channel for more content.");
        }
        else
        {
            Debug.LogError("DemoCaller: TTSClient not assigned!");
        }
    }

    void OnDestroy()
    {
        if (fastAPIClient != null)
        {
            fastAPIClient.StopSpeech();
        }
    }
}